[theme]
# Primary accent color for interactive elements.
primaryColor = "#CDA34F"

# Background color for the main content area.
backgroundColor = "#373F27"

# Background color used for the sidebar and most interactive widgets.
secondaryBackgroundColor = "#636B46"

# Color used for almost all text.
textColor = "#E9E7DA"
